<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product-image</name>
   <tag></tag>
   <elementGuidId>a9af9a8c-7ed9-4192-8636-e95026e3342a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;8070451214075707112&quot;]/div[2]/a/picture/img[count(. | //img[@src = 'https://n2.sdlcdn.com/imgs/h/e/q/230X258_sharpened/1P-90790.webp' and @title = 'Samsung Galaxy J8 (64GB, 4GB RAM) - 6']) = count(//img[@src = 'https://n2.sdlcdn.com/imgs/h/e/q/230X258_sharpened/1P-90790.webp' and @title = 'Samsung Galaxy J8 (64GB, 4GB RAM) - 6'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://n2.sdlcdn.com/imgs/h/e/q/230X258_sharpened/1P-90790.webp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Samsung Galaxy J8 (64GB, 4GB RAM) - 6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;8070451214075707112&quot;]/div[2]/a/picture/img</value>
   </webElementProperties>
</WebElementEntity>
