<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cart2</name>
   <tag></tag>
   <elementGuidId>d8a689e7-2367-4f56-a468-ff6bea9c3009</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cartInner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	 				Cart
					2
				</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sdHeader&quot;)/div[@class=&quot;headerBar reset-padding&quot;]/div[@class=&quot;topBar  headWrapper  top-freeze-reference-point&quot;]/div[@class=&quot;header_wrapper&quot;]/div[@class=&quot;col-xs-5 reset-padding header-right rfloat&quot;]/div[@class=&quot;cartContainer col-xs-11 reset-padding&quot;]/div[@class=&quot;cartInner&quot;]</value>
   </webElementProperties>
</WebElementEntity>
