<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Intex</name>
   <tag></tag>
   <elementGuidId>2abe63fb-0cb3-47fe-be2b-9f7985ba0ac6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intex</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_wrapper&quot;)/section[@class=&quot;home-page-right-section animScroll sliderHomeWidget&quot;]/section[@class=&quot;home-page-right-card dp-click-widgets&quot;]/div[@class=&quot;main-banner-wrapper adtechBannerHomePage dp-widget posRelative dp-fired&quot;]/div[@class=&quot;banner-link bar&quot;]/div[@class=&quot;banner-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
